package com.tsystems.si.aviation.img.imgXssReceiver.bean;

// Generated Jun 19, 2015 10:35:39 AM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Flightinfo generated by hbm2java
 */
public class Flightinfo implements java.io.Serializable {

	private Integer id;
	private Date flightScheduledDate;
	private String flightIdentity;
	private String callSign;
	private String flightDirection;
	private Date flightScheduledDateTime;
	private String estimatedTakeOffDateTime;
	private String estimatedLandingDateTime;
	private String shareFlightIdentity;
	private String atot;
	private String aibt;
	private String peratot;
	private String aobt;
	private String aldt;
	private String createtime;
	private String updatetime;
	private String iataoriginAirport;
	private String iatapreviousAirport;
	private String iataviaAirport;
	private String iatanextAirport;
	private String iatadestinationAirport;
	private String registration;

	public Flightinfo() {
	}

	public Flightinfo(Date flightScheduledDate, String flightIdentity,
			String callSign, String flightDirection,
			Date flightScheduledDateTime, String estimatedTakeOffDateTime,
			String estimatedLandingDateTime, String shareFlightIdentity,
			String atot, String aibt, String peratot, String aobt, String aldt,
			String createtime, String updatetime, String iataoriginAirport,
			String iatapreviousAirport, String iataviaAirport,
			String iatanextAirport, String iatadestinationAirport,
			String registration) {
		this.flightScheduledDate = flightScheduledDate;
		this.flightIdentity = flightIdentity;
		this.callSign = callSign;
		this.flightDirection = flightDirection;
		this.flightScheduledDateTime = flightScheduledDateTime;
		this.estimatedTakeOffDateTime = estimatedTakeOffDateTime;
		this.estimatedLandingDateTime = estimatedLandingDateTime;
		this.shareFlightIdentity = shareFlightIdentity;
		this.atot = atot;
		this.aibt = aibt;
		this.peratot = peratot;
		this.aobt = aobt;
		this.aldt = aldt;
		this.createtime = createtime;
		this.updatetime = updatetime;
		this.iataoriginAirport = iataoriginAirport;
		this.iatapreviousAirport = iatapreviousAirport;
		this.iataviaAirport = iataviaAirport;
		this.iatanextAirport = iatanextAirport;
		this.iatadestinationAirport = iatadestinationAirport;
		this.registration = registration;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Date getFlightScheduledDate() {
		return this.flightScheduledDate;
	}

	public void setFlightScheduledDate(Date flightScheduledDate) {
		this.flightScheduledDate = flightScheduledDate;
	}

	public String getFlightIdentity() {
		return this.flightIdentity;
	}

	public void setFlightIdentity(String flightIdentity) {
		this.flightIdentity = flightIdentity;
	}

	public String getCallSign() {
		return this.callSign;
	}

	public void setCallSign(String callSign) {
		this.callSign = callSign;
	}

	public String getFlightDirection() {
		return this.flightDirection;
	}

	public void setFlightDirection(String flightDirection) {
		this.flightDirection = flightDirection;
	}

	public Date getFlightScheduledDateTime() {
		return this.flightScheduledDateTime;
	}

	public void setFlightScheduledDateTime(Date flightScheduledDateTime) {
		this.flightScheduledDateTime = flightScheduledDateTime;
	}

	public String getEstimatedTakeOffDateTime() {
		return this.estimatedTakeOffDateTime;
	}

	public void setEstimatedTakeOffDateTime(String estimatedTakeOffDateTime) {
		this.estimatedTakeOffDateTime = estimatedTakeOffDateTime;
	}

	public String getEstimatedLandingDateTime() {
		return this.estimatedLandingDateTime;
	}

	public void setEstimatedLandingDateTime(String estimatedLandingDateTime) {
		this.estimatedLandingDateTime = estimatedLandingDateTime;
	}

	public String getShareFlightIdentity() {
		return this.shareFlightIdentity;
	}

	public void setShareFlightIdentity(String shareFlightIdentity) {
		this.shareFlightIdentity = shareFlightIdentity;
	}

	public String getAtot() {
		return this.atot;
	}

	public void setAtot(String atot) {
		this.atot = atot;
	}

	public String getAibt() {
		return this.aibt;
	}

	public void setAibt(String aibt) {
		this.aibt = aibt;
	}

	public String getPeratot() {
		return this.peratot;
	}

	public void setPeratot(String peratot) {
		this.peratot = peratot;
	}

	public String getAobt() {
		return this.aobt;
	}

	public void setAobt(String aobt) {
		this.aobt = aobt;
	}

	public String getAldt() {
		return this.aldt;
	}

	public void setAldt(String aldt) {
		this.aldt = aldt;
	}

	public String getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(String createtime) {
		this.createtime = createtime;
	}

	public String getUpdatetime() {
		return this.updatetime;
	}

	public void setUpdatetime(String updatetime) {
		this.updatetime = updatetime;
	}

	public String getIataoriginAirport() {
		return this.iataoriginAirport;
	}

	public void setIataoriginAirport(String iataoriginAirport) {
		this.iataoriginAirport = iataoriginAirport;
	}

	public String getIatapreviousAirport() {
		return this.iatapreviousAirport;
	}

	public void setIatapreviousAirport(String iatapreviousAirport) {
		this.iatapreviousAirport = iatapreviousAirport;
	}

	public String getIataviaAirport() {
		return this.iataviaAirport;
	}

	public void setIataviaAirport(String iataviaAirport) {
		this.iataviaAirport = iataviaAirport;
	}

	public String getIatanextAirport() {
		return this.iatanextAirport;
	}

	public void setIatanextAirport(String iatanextAirport) {
		this.iatanextAirport = iatanextAirport;
	}

	public String getIatadestinationAirport() {
		return this.iatadestinationAirport;
	}

	public void setIatadestinationAirport(String iatadestinationAirport) {
		this.iatadestinationAirport = iatadestinationAirport;
	}

	public String getRegistration() {
		return this.registration;
	}

	public void setRegistration(String registration) {
		this.registration = registration;
	}

	@Override
	public String toString() {
		return String
				.format("Flightinfo [id=%s, flightIdentity=%s, flightDirection=%s, callSign=%s, registration=%s, flightScheduledDate=%s, flightScheduledDateTime=%s, peratot=%s, aldt=%s, aibt=%s, aobt=%s, atot=%s, shareFlightIdentity=%s, createtime=%s, updatetime=%s, estimatedLandingDateTime=%s, estimatedTakeOffDateTime=%s, iataoriginAirport=%s, iatapreviousAirport=%s, iataviaAirport=%s, iatanextAirport=%s, iatadestinationAirport=%s]",
						id, flightIdentity, flightDirection, callSign,
						registration, flightScheduledDate,
						flightScheduledDateTime, peratot, aldt, aibt, aobt,
						atot, shareFlightIdentity, createtime, updatetime,
						estimatedLandingDateTime, estimatedTakeOffDateTime,
						iataoriginAirport, iatapreviousAirport, iataviaAirport,
						iatanextAirport, iatadestinationAirport);
	}

}
