package com.tsystems.si.aviation.img.imgXssReceiver.bean;

// Generated Jun 19, 2015 10:35:39 AM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * XmlMessageLog generated by hbm2java
 */
public class XmlMessageLog implements java.io.Serializable {

	private Long id;
	private Long messageId;
	private String filename;
	private String flightDirection;
	private String flightScheduledDate;
	private String flightScheduledDateTime;
	private String flightnumber;
	private String reg;
	private String takeoffairport;
	private String landairport;
	private String takeofftime;
	private String pretakeofftime;
	private String landtime;
	private String nextlandtime;
	private String xmlmsg;
	private Date createtime;
	private Date sendtime;
	private String status;
	private String orgMessageSendTime;
	private String usState;

	public XmlMessageLog() {
	}

	public XmlMessageLog(Long messageId, String filename,
			String flightDirection, String flightScheduledDate,
			String flightScheduledDateTime, String flightnumber, String reg,
			String takeoffairport, String landairport, String takeofftime,
			String pretakeofftime, String landtime, String nextlandtime,
			String xmlmsg, Date createtime, Date sendtime, String status,
			String orgMessageSendTime, String usState) {
		this.messageId = messageId;
		this.filename = filename;
		this.flightDirection = flightDirection;
		this.flightScheduledDate = flightScheduledDate;
		this.flightScheduledDateTime = flightScheduledDateTime;
		this.flightnumber = flightnumber;
		this.reg = reg;
		this.takeoffairport = takeoffairport;
		this.landairport = landairport;
		this.takeofftime = takeofftime;
		this.pretakeofftime = pretakeofftime;
		this.landtime = landtime;
		this.nextlandtime = nextlandtime;
		this.xmlmsg = xmlmsg;
		this.createtime = createtime;
		this.sendtime = sendtime;
		this.status = status;
		this.orgMessageSendTime = orgMessageSendTime;
		this.usState = usState;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getMessageId() {
		return this.messageId;
	}

	public void setMessageId(Long messageId) {
		this.messageId = messageId;
	}

	public String getFilename() {
		return this.filename;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}

	public String getFlightDirection() {
		return this.flightDirection;
	}

	public void setFlightDirection(String flightDirection) {
		this.flightDirection = flightDirection;
	}

	public String getFlightScheduledDate() {
		return this.flightScheduledDate;
	}

	public void setFlightScheduledDate(String flightScheduledDate) {
		this.flightScheduledDate = flightScheduledDate;
	}

	public String getFlightScheduledDateTime() {
		return this.flightScheduledDateTime;
	}

	public void setFlightScheduledDateTime(String flightScheduledDateTime) {
		this.flightScheduledDateTime = flightScheduledDateTime;
	}

	public String getFlightnumber() {
		return this.flightnumber;
	}

	public void setFlightnumber(String flightnumber) {
		this.flightnumber = flightnumber;
	}

	public String getReg() {
		return this.reg;
	}

	public void setReg(String reg) {
		this.reg = reg;
	}

	public String getTakeoffairport() {
		return this.takeoffairport;
	}

	public void setTakeoffairport(String takeoffairport) {
		this.takeoffairport = takeoffairport;
	}

	public String getLandairport() {
		return this.landairport;
	}

	public void setLandairport(String landairport) {
		this.landairport = landairport;
	}

	public String getTakeofftime() {
		return this.takeofftime;
	}

	public void setTakeofftime(String takeofftime) {
		this.takeofftime = takeofftime;
	}

	public String getPretakeofftime() {
		return this.pretakeofftime;
	}

	public void setPretakeofftime(String pretakeofftime) {
		this.pretakeofftime = pretakeofftime;
	}

	public String getLandtime() {
		return this.landtime;
	}

	public void setLandtime(String landtime) {
		this.landtime = landtime;
	}

	public String getNextlandtime() {
		return this.nextlandtime;
	}

	public void setNextlandtime(String nextlandtime) {
		this.nextlandtime = nextlandtime;
	}

	public String getXmlmsg() {
		return this.xmlmsg;
	}

	public void setXmlmsg(String xmlmsg) {
		this.xmlmsg = xmlmsg;
	}

	public Date getCreatetime() {
		return this.createtime;
	}

	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	public Date getSendtime() {
		return this.sendtime;
	}

	public void setSendtime(Date sendtime) {
		this.sendtime = sendtime;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getOrgMessageSendTime() {
		return this.orgMessageSendTime;
	}

	public void setOrgMessageSendTime(String orgMessageSendTime) {
		this.orgMessageSendTime = orgMessageSendTime;
	}

	public String getUsState() {
		return this.usState;
	}

	public void setUsState(String usState) {
		this.usState = usState;
	}

}
